const tracks=window.tracks, modules=window.modules;
const ids=Object.keys(modules);
const storage={
  get(key){try{return window.localStorage.getItem(key)}catch(e){return null}},
  set(key,val){try{window.localStorage.setItem(key,val);return true}catch(e){return false}}
};
let progress={};
try{progress=JSON.parse(storage.get('thinklab_complete_v2')||storage.get('thinklab_complete_v1')||'{}')}catch(e){progress={}};
let state={view:'train',track:null,module:null,stage:null,qi:0,selected:null,last:'',coachQueue:[],coachIndex:0,coachAnswers:[],firstScore:0,quizCorrect:0,quizAnswered:0};
const app=document.getElementById('app');
const weaknessMeta={
 framing:{name:'Problem framing',desc:'Clarify the objective, scope and success metric before solving.',keys:['clarif','objective','goal','define','scope'],challenge:'Before solving, state the objective, scope and success metric in 1–2 sentences.'},
 structure:{name:'Decomposition',desc:'Break ambiguity into mutually useful drivers instead of listing tactics.',keys:['break','decom','driver','funnel','segment','stage','bucket'],challenge:'Break this problem into 3–4 non-overlapping drivers. Do not propose solutions yet.'},
 hypotheses:{name:'Hypothesis thinking',desc:'Form plausible explanations and say what evidence would distinguish them.',keys:['hypoth','could','might','cause','assum','likely'],challenge:'State your top 2 hypotheses. What evidence would confirm or reject each one?'},
 evidence:{name:'Evidence & metrics',desc:'Name the exact data needed to test your reasoning.',keys:['data','metric','measure','compare','cohort','evidence','check','baseline'],challenge:'What are the first 3 pieces of data you would request, and what would each tell you?'},
 prioritisation:{name:'Prioritisation',desc:'Choose what matters first and justify it by impact, likelihood or cost.',keys:['priorit','first','largest','impact','because','trade','rank'],challenge:'Choose ONE thing you would investigate or do first. Why that before everything else?'},
 synthesis:{name:'Synthesis & recommendation',desc:'Turn analysis into a clear recommendation, trade-off and success measure.',keys:['recommend','therefore','would do','next','success','monitor','conclusion'],challenge:'Give your recommendation in 3 sentences: decision, rationale, and success metric.'}
};
function coachData(){return progress._coach||(progress._coach={weaknesses:{},sessions:0,improvements:[],lastPatterns:[]})}
const save=()=>storage.set('thinklab_complete_v2',JSON.stringify(progress));
function p(id){return progress[id]||(progress[id]={lesson:false,quiz:0,test:0,attempts:0,last:0})}
function mastery(id){const x=p(id);return Math.round((x.lesson?30:0)+(x.quiz*.4)+(x.test*.3))}
function readiness(){return Math.round(ids.reduce((s,id)=>s+mastery(id),0)/ids.length)}
function knowledgeReadiness(){return Math.round(ids.reduce((sum,id)=>{let x=p(id);return sum+((x.lesson?30:0)+(x.quiz*.4))/70*100},0)/ids.length)}
function weaknessScore(k){return coachData().weaknesses[k]||0}
function weakestPattern(){return Object.keys(weaknessMeta).sort((a,b)=>weaknessScore(b)-weaknessScore(a))[0]}
function weakest(){let pat=weakestPattern(), candidates=ids.filter(id=>{let m=modules[id], text=(m.title+' '+m.desc+' '+m.skills.join(' ')).toLowerCase(); let map={framing:['fram','clarif'],structure:['decom','root','case structur'],hypotheses:['hypoth','root'],evidence:['metric','experiment','data','exhibit'],prioritisation:['priorit','trade','execution'],synthesis:['synth','communication','recommend']};return (map[pat]||[]).some(k=>text.includes(k))});let pool=candidates.length?candidates:ids;return pool.slice().sort((a,b)=>mastery(a)-mastery(b))[0]}
function doneCount(){return ids.filter(id=>mastery(id)>=70).length}
function render(){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('on',b.dataset.nav===state.view)); if(state.stage==='lesson')return lesson(); if(state.stage==='quiz')return quiz(); if(state.stage==='review')return review(); if(state.stage==='case')return caseView(); if(state.stage==='feedback')return feedback(); if(state.stage==='coachChallenge')return coachChallenge(); if(state.stage==='coachRevise')return coachRevise(); if(state.stage==='coachResult')return coachResult(); if(state.view==='train')return train(); if(state.view==='library')return library(); if(state.view==='coach')return coachHome(); return prog();}
function train(){if(state.track)return trackView();let weak=weakest(),r=readiness();app.innerHTML=`<section class="page"><div class="hero"><div class="ey">ANALYTICS LAB</div><h1>Interview Training</h1><p>Lessons and practice across analytical thinking, product, strategy, growth, business, leadership and case interviews.</p></div><div class="grid">${Object.entries(tracks).map(([k,t])=>`<div class="card" data-track="${k}"><div class="ico">${t.icon}</div><div><strong>${t.name}</strong><small>${t.desc}</small></div><span class="arr">→</span></div>`).join('')}</div><div class="today"><div><strong>${r===0?'Start with a true baseline':'Recommended next: '+modules[weak].title}</strong><p>${r===0?'Your readiness score starts against all 45 modules, so progress is not inflated by unstarted topics.':'Your current overall readiness is '+r+'%. The recommendation targets your lowest mastery area.'}</p></div><button class="btn" id="start">${r===0?'Begin curriculum':'Train weakest skill'}</button></div></section>`;document.querySelectorAll('[data-track]').forEach(x=>x.onclick=()=>{state.track=x.dataset.track;render()});document.getElementById('start').onclick=()=>{state.module=weak;state.track=modules[weak].track;state.stage='lesson';render()}}
function knowledgeComplete(id){let x=p(id);return !!x.lesson&&x.quiz>=70}
function trackKnowledgeCount(track){return ids.filter(id=>modules[id].track===track&&knowledgeComplete(id)).length}
function caseUnlocked(id){let m=modules[id];return knowledgeComplete(id)&&trackKnowledgeCount(m.track)>=3}
function planBar(active){let steps=[['1','Learn'],['2','Examples'],['3','MCQ drills'],['4','Scenarios'],['5','Written case later']];return `<div class="lessonPlan">${steps.map((z,i)=>`<div class="lessonStep ${i===active?'on':''}"><strong>${z[0]} · ${z[1]}</strong><span>${['Build the concept','See it applied','Recognise strong reasoning','Choose under ambiguity','Produce a full answer'][i]}</span></div>`).join('')}</div>`}
function trackGuidance(track){let g={
 analytical:{why:'Interviewers want to see whether you can turn ambiguity into a solvable problem without jumping to an attractive solution.',mistakes:['Starting with solutions before defining the problem','Listing every possible cause without prioritising','Using data words without naming the exact metric or comparison']},
 quant:{why:'You do not need advanced mathematics. You need to translate business questions into simple equations, calculate accurately, and interpret what the number means.',mistakes:['Calculating before defining the metric','Confusing percentage change with percentage points','Reporting a number without explaining the business implication']},
 product:{why:'Strong product answers connect a real user problem to evidence, trade-offs, product decisions and measurable outcomes.',mistakes:['Feature brainstorming before identifying the user problem','Using frameworks mechanically','Talking about collaboration instead of your decision and impact']},
 strategy:{why:'Strategy interviews test whether you can make a choice with incomplete information and explain why that choice is better than realistic alternatives.',mistakes:['Calling a list of ideas a strategy','Ignoring economics or competitive response','Giving a recommendation without stating the trade-off']},
 growth:{why:'Growth answers should diagnose where the system is constrained before proposing tactics. The best lever depends on the bottleneck.',mistakes:['Jumping straight to acquisition','Optimising a local metric while hurting retention or margin','Listing experiments without a hypothesis']},
 leadership:{why:'Leadership questions are strongest when you show judgment: the conflict, your decision, how you influenced others, and what changed.',mistakes:['Making the story mostly about being nice or communicative','Avoiding the actual disagreement or trade-off','Using “we” so much that your contribution disappears']},
 cases:{why:'Case interviews reward a transparent thinking process: clarify, structure, analyse, prioritise and synthesise.',mistakes:['Forcing a memorised framework onto the problem','Boiling the ocean instead of following the highest-value branch','Ending analysis without a recommendation']},
 communication:{why:'The interviewer needs to follow your thinking. Senior communication makes the conclusion visible early and uses detail only to support it.',mistakes:['Giving background before answering the question','Hiding the decision inside a long story','Confusing confidence with certainty when assumptions are still untested']}
};return g[track]||g.analytical}
