// Final QA teaching layer. Uses direct global bindings so every screen gets the same style.
(function(){
const MORE={
 analytical:[['Payments','Payment success fell from 94% to 86%. Check where it fell before guessing why.'],['Support','Tickets doubled. Find out whether more users have problems or one problem is creating more tickets.'],['Fraud','Fraud losses rose. Separate more fraud attempts from worse detection.'],['Subscriptions','Cancellations rose after renewal. Check price, payment failures, product value, and customer mix separately.']],
 quant:[['Percentage points','Conversion moved from 20% to 25%. That is +5 percentage points, or a 25% relative increase.'],['Payback','You spend €100 to acquire a customer and earn €20 contribution each month. Rough payback is 5 months.'],['Forecast','Sales grew 10% last month. That does not mean next month will also grow 10%. Ask what caused the change.'],['Sample size','A test with 40 users can look dramatic by chance. More data helps you tell signal from noise.']],
 product:[['Password reset','Users leave after the reset email step. The email may be late, in spam, or expired. Each needs a different fix.'],['Search filters','Ten new filters may add control but also make the page harder to use. More features are not automatically better.'],['Food delivery','Customers ask for live driver location. First learn whether the real pain is uncertainty, late orders, or bad ETAs.'],['B2B workflow','Users export to Excel every day. Learn what they do there before building another feature.']],
 strategy:[['Country expansion','A big market can still be a bad entry choice if regulation, competition, or distribution makes winning too expensive.'],['Premium tier','A premium plan only works if enough customers value the extra benefits more than the higher price.'],['Platform bet','A platform investment may be slow now but make many future products cheaper. Compare today’s cost with future leverage.'],['Channel choice','Direct sales gives more control but costs more. Partnerships scale faster but share economics and customer access.']],
 growth:[['Retention','If day-30 retention improves from 20% to 30%, every future acquisition campaign becomes more valuable.'],['SEO','Traffic doubles from search, but none of it activates. The channel grew; the business did not.'],['Pricing','A 10% price rise can increase revenue even with some churn, but only if lost customers do not outweigh the higher price.'],['Referral loop','If each happy user brings 0.2 new users, referrals help growth but do not sustain it alone.']],
 leadership:[['Roadmap conflict','A VP wants a feature this month; engineering needs six weeks. The choices are smaller scope, a later date, or more risk.'],['Legal review','Legal blocks launch. Find the exact risk and see whether scope or rollout can change.'],['Executive pushback','A senior leader disagrees. Show the evidence and say what new information would change your view.'],['Team ownership','Two teams think the other owns the problem. Make the owner and next decision explicit.']],
 cases:[['Restaurant profit','A restaurant is less profitable. Check revenue and cost first, then price, volume, food cost, labour, and rent.'],['Airline route','Before launching a route, check demand, ticket economics, aircraft use, competition, and operations.'],['App decline','Daily users fell. Separate fewer new users, weaker activation, and worse retention.'],['Factory delay','Output fell. Check machine downtime, staffing, materials, demand, and bottlenecks before recommending automation.']],
 communication:[['Board update','Start with: “Revenue is down 8%, mainly because repeat purchases fell. I would fix retention before buying more acquisition.”'],['Bad news','Say the issue early: “We will miss the date by two weeks because testing found a payment risk.” Then explain options.'],['Recommendation','Instead of listing five ideas, say which one you choose, why, and what you would watch.'],['Challenge','If someone pushes back, answer the objection directly before adding more background.']]
};
Object.keys(MORE).forEach(k=>{if(AL_SIMPLE_EXAMPLES[k])AL_SIMPLE_EXAMPLES[k].push(...MORE[k]);});

trackGuidance=function(track){const g={
 analytical:{why:'Make the problem clear before trying to fix it.',mistakes:['Jumping to a solution too early','Listing lots of causes without deciding what to check first','Saying “look at the data” without naming the data you need']},
 quant:{why:'Use simple numbers to understand what is happening and what to do next.',mistakes:['Calculating before you know what the number means','Mixing up percentage change and percentage points','Giving a number without explaining why it matters']},
 product:{why:'Understand the user problem first. Then decide what change is worth making.',mistakes:['Brainstorming features before understanding the problem','Using a framework just because you remember it','Talking about teamwork instead of the decision you made']},
 strategy:{why:'Compare real choices, pick one, and explain what you gain and give up.',mistakes:['Calling a list of ideas a strategy','Ignoring money, competition, or execution limits','Recommending something without saying the trade-off']},
 growth:{why:'Find where growth is leaking before choosing a tactic.',mistakes:['Assuming the answer is always more acquisition','Improving one metric while hurting retention or margin','Running experiments without a clear reason']},
 leadership:{why:'Show the difficult situation, the choice you made, and how you moved people forward.',mistakes:['Only saying you communicated well','Hiding the real disagreement','Using “we” so much that your own role disappears']},
 cases:{why:'Break the question into smaller parts, follow the evidence, and make a recommendation.',mistakes:['Forcing a memorised framework onto every case','Trying to analyse everything at once','Ending without a clear recommendation']},
 communication:{why:'Say the answer clearly, then give the few points that support it.',mistakes:['Giving lots of background before answering','Burying the decision inside a long story','Sounding certain when the evidence is still weak']}
};return g[track]||g.analytical;};

function pickFresh(track,key,offset){const arr=AL_SIMPLE_EXAMPLES[track]||AL_SIMPLE_EXAMPLES.analytical;let n=offset||0;const s=String(key||'');for(let i=0;i<s.length;i++)n=(n+s.charCodeAt(i)*(i+3))%997;return arr[n%arr.length];}
alTrackExplain=function(track,c){const ex=pickFresh(track,c,1);const intro={analytical:'Make this specific enough that you know what to check next.',quant:'Ask what this number tells you, not just how to calculate it.',product:'Connect this back to a real user problem.',strategy:'Use this to make a choice, not a longer list.',growth:'Use this to find the weak part of the growth system.',leadership:'Use this to show your own judgment and influence.',cases:'Use this to make the big problem smaller.',communication:'Use this to make your answer easier to follow.'};return `${intro[track]||intro.analytical}<span class="al-everyday-example"><b>Example:</b> ${alGloss(ex[1])}</span>`;};

alCompare=function(m,g){const a=pickFresh(m.track,m.title,3),b=pickFresh(m.track,m.title,7);const good=(m.case.model||[])[0]||m.concepts[0]||m.desc;return `<div class="al-compare"><div class="al-side al-bad"><div class="miniLabel">EASY TRAP</div><strong>${alGloss(g.mistakes[0])}</strong><p><b>Example:</b> ${alGloss(a[1])}</p></div><div class="al-side al-good"><div class="miniLabel">BETTER MOVE</div><strong>${alGloss(good)}</strong><p><b>Different example:</b> ${alGloss(b[1])}</p></div></div>`;};

quizBank=function(id){const m=modules[id],g=trackGuidance(m.track),model=m.case.model||[],c=m.concepts||[];const first=model[0]||m.case.hint||c[0],second=model[1]||c[1]||'check the biggest change',third=model[2]||c[2]||'compare the next explanation';const ex=i=>pickFresh(m.track,id,i).1;};
// The line above is intentionally replaced below; keeping quiz construction explicit makes QA easier.
quizBank=function(id){const m=modules[id],g=trackGuidance(m.track),model=m.case.model||[],c=m.concepts||[];const first=model[0]||m.case.hint||c[0],second=model[1]||c[1]||'check the biggest change',third=model[2]||c[2]||'compare the next explanation';const ex=i=>pickFresh(m.track,id,i)[1];return [
 [`What is the best way to start <strong>${alGloss(m.title)}</strong>?`,[first,second,'Ask for more data before deciding what question you are trying to answer.','Start with the solution that sounds most likely and prove it.'],0,`Start by making the problem clear. Then the next steps have a purpose.<span class="al-everyday-example"><b>Example:</b> ${alGloss(ex(1))}</span>`,['Best start: it gives the rest of the analysis a clear target.','Useful, but usually one step too early.','More data does not help if you have not decided what you are trying to learn.','This can trap you into defending the first idea instead of testing it.']],
 [`In this case:<br><br><em>${alGloss(m.case.prompt)}</em><br><br>What would you do <strong>first</strong>?`,[first,second,third,'Look at a competitor first and copy the strongest-looking approach.'],0,`Several options may be useful later. The question is which one should come first.<span class="al-everyday-example"><b>Another example:</b> ${alGloss(ex(2))}</span>`,['Best first move because it tells you what problem you are actually solving.','Reasonable later, but it assumes the first question is already clear.','Also useful later, but it narrows the problem too soon.','Competitors can give ideas, but their users, economics, and constraints may be different.']],
 ['Which order makes the most sense?',[`${first} → ${second} → ${third}`,`${second} → ${first} → ${third}`,`${third} → ${first} → ${second}`,'Recommendation → data → problem definition'],0,`The order matters because each step should help you decide the next one.<span class="al-everyday-example"><b>Example:</b> ${alGloss(ex(3))}</span>`,['Good order: start broad enough, then narrow.','Tempting, but you are analysing before you know exactly what you are analysing for.','This starts too narrow and can make you miss the real problem.','This starts with an answer and works backwards to justify it.']],
 ['Which evidence would be most useful?',['Data that directly tests the main question for the right users and time period, compared with a useful baseline.','The overall average because it is simple and easy to explain.','Only the latest week because old data may be irrelevant.','Only customer interviews because they explain why people behave the way they do.'],0,`Use evidence that can actually change your view.<span class="al-everyday-example"><b>Example:</b> ${alGloss(ex(4))}</span>`,['Best choice: it connects the data to the question.','Averages can hide what is happening in one group.','One week without a comparison tells you very little.','Interviews are useful, but they do not tell you how common or large the problem is.']],
 ['Which mistake is most damaging here?',[g.mistakes[0],'Saying what assumption you are making.','Choosing one priority and explaining why.','Changing your view when new evidence disagrees with you.'],0,`${g.mistakes[0]} can make the whole answer go in the wrong direction.<span class="al-everyday-example"><b>Different example:</b> ${alGloss(ex(5))}</span>`,['This is the problem. Fix it before going deeper.','This is good practice. It makes your reasoning visible.','This is also good practice. Interviews usually reward a clear choice.','This is strong thinking. Evidence should be allowed to change your answer.']]
 ];};

Object.assign(weaknessMeta,{framing:{...weaknessMeta.framing,desc:'Say what problem you are solving, for whom, and how you will know it is better.',challenge:'In 1–2 sentences: what exactly are you trying to improve, for which users, and with which metric?'},structure:{...weaknessMeta.structure,desc:'Break the problem into a few useful parts instead of jumping to fixes.',challenge:'Split the problem into 3–4 parts you could check separately. Do not suggest fixes yet.'},hypotheses:{...weaknessMeta.hypotheses,desc:'Give a few possible explanations and say what evidence would support each one.',challenge:'Give your top 2 explanations. What would you expect to see if each one were true?'},evidence:{...weaknessMeta.evidence,desc:'Name the exact data you would check and what it would tell you.',challenge:'What are the first 3 pieces of data you would ask for? Say what each one would help you learn.'},prioritisation:{...weaknessMeta.prioritisation,desc:'Choose what you would do first and explain why it comes before the other options.',challenge:'Pick ONE thing to investigate or do first. Why that one?'},synthesis:{...weaknessMeta.synthesis,desc:'Finish with a clear recommendation and how you would measure whether it worked.',challenge:'Give your answer in 3 sentences: what you would do, why, and how you would know it worked.'}});

const baseReview=review;review=function(){baseReview();const c=document.querySelector('#app .content'),m=modules[state.module];if(c&&m&&!c.querySelector('.al-review-example')){const ex=pickFresh(m.track,m.title,11);const card=document.createElement('div');card.className='al-review-example';card.innerHTML=`<div class="miniLabel">ONE MORE EXAMPLE</div><strong>${alGloss(ex[0])}</strong><p>${alGloss(ex[1])}</p>`;const actions=c.querySelector('.actions');if(actions)actions.insertAdjacentElement('beforebegin',card);alBindTerms();}};

function plainCopy(){const swaps={'What this skill actually means':'What this means','In simple terms:':'Plain English:','The goal is to strengthen one thinking muscle at a time.':'Focus on this one part first.','The important signal is whether your reasoning became more explicit and decision-oriented after challenge.':'Compare the two answers. Is the second one clearer, more specific, and easier to follow?','This score is less important than what happens next. The coach will target the reasoning steps your answer did not make visible.':'The score is only a rough guide. Look at what you missed, fix it, and try again.','Do not look at the model reasoning yet.':'Try once more before looking at the model answer.','Use this to inspect gaps. Do not memorise the wording.':'Compare the logic with yours. Do not memorise the wording.'};document.querySelectorAll('#app h1,#app h2,#app h3,#app p,#app span,#app strong,#app li').forEach(el=>{if(el.children.length)return;const t=el.textContent.trim();if(swaps[t])el.textContent=swaps[t];});}
const baseRender=render;render=function(){baseRender();plainCopy();};
})();